"""
Settings and configuration for the server.
"""
import os

APP_DIRECTORY = os.getcwd() + '/'  # The path to the root of the project.
ALGORITHM_ROOT_DIRECTORY = APP_DIRECTORY + 'res/algorithms/'  # The path to the root of the stored algorithms.
JAVA_DIRECTORY = ALGORITHM_ROOT_DIRECTORY + 'java/'  # The path to the stored Java algorithms.
PYTHON_DIRECTORY = ALGORITHM_ROOT_DIRECTORY + 'python/'  # The path to the stores Python algorithms.
TEMP_COMPILATION_DIRECTORY = APP_DIRECTORY + 'temp/'  # The path to the temporary files generated by the server.

AFFORDABLE_INT_LIMIT = 10000000  # The upper bound for random integer numbers.
MULTIPLY_FACTOR = 10  # The multiplication factor by which random numbers are increased.
RUN_TIME_LIMIT = 120  # The affordable execution time for an algorithm.
